import { createPublicClient, http, formatGwei } from "viem";
import { base, arbitrum, optimism } from "viem/chains";
import type { Skill } from "./types.js";

interface L2Data {
  name: string;
  gasPrice: string;
  tps: string;
  bridge: string;
  devTooling: string;
  tvl: string;
  launched: string;
}

export const comparisonTableSkill: Skill = {
  name: "comparison-table",
  keywords: [
    "comparison",
    "table",
    "base",
    "arbitrum",
    "optimism",
    "gas",
    "tps",
    "bridge",
  ],

  async execute(): Promise<string> {
    console.log("[comparison-table] Fetching L2 gas prices...");

    // Fetch live gas prices from all 3 L2s in parallel
    const results = await Promise.allSettled([
      createPublicClient({
        chain: base,
        transport: http("https://mainnet.base.org"),
      }).getGasPrice(),
      createPublicClient({
        chain: arbitrum,
        transport: http("https://arb1.arbitrum.io/rpc"),
      }).getGasPrice(),
      createPublicClient({
        chain: optimism,
        transport: http("https://mainnet.optimism.io"),
      }).getGasPrice(),
    ]);

    const gasBase =
      results[0].status === "fulfilled"
        ? formatGwei(results[0].value)
        : "N/A";
    const gasArbitrum =
      results[1].status === "fulfilled"
        ? formatGwei(results[1].value)
        : "N/A";
    const gasOptimism =
      results[2].status === "fulfilled"
        ? formatGwei(results[2].value)
        : "N/A";

    const chains: L2Data[] = [
      {
        name: "Base",
        gasPrice: `${gasBase} Gwei`,
        tps: "~30-60",
        bridge: "Base Bridge (native), Across, Stargate",
        devTooling: "Hardhat, Foundry, Remix, Coinbase SDK",
        tvl: "~$8B+",
        launched: "Aug 2023",
      },
      {
        name: "Arbitrum One",
        gasPrice: `${gasArbitrum} Gwei`,
        tps: "~40-80",
        bridge: "Arbitrum Bridge (native), Across, Hop",
        devTooling: "Hardhat, Foundry, Stylus (Rust/C++)",
        tvl: "~$12B+",
        launched: "Aug 2021",
      },
      {
        name: "Optimism",
        gasPrice: `${gasOptimism} Gwei`,
        tps: "~30-60",
        bridge: "OP Bridge (native), Across, Stargate",
        devTooling: "Hardhat, Foundry, OP Stack",
        tvl: "~$6B+",
        launched: "Jan 2022",
      },
    ];

    const lines = [
      "# L2 Chain Comparison: Base vs Arbitrum vs Optimism",
      "",
      "## Live Gas Prices",
      "",
      "| Chain | Gas Price | TPS | Launched |",
      "|-------|----------|-----|----------|",
    ];

    for (const c of chains) {
      lines.push(`| ${c.name} | ${c.gasPrice} | ${c.tps} | ${c.launched} |`);
    }

    lines.push(
      "",
      "## Bridging Options",
      "",
      "| Chain | Native Bridge | Third-Party |",
      "|-------|--------------|-------------|",
    );

    for (const c of chains) {
      const [native, ...thirdParty] = c.bridge.split(", ");
      lines.push(`| ${c.name} | ${native} | ${thirdParty.join(", ")} |`);
    }

    lines.push(
      "",
      "## Developer Tooling",
      "",
      "| Chain | Tooling |",
      "|-------|---------|",
    );

    for (const c of chains) {
      lines.push(`| ${c.name} | ${c.devTooling} |`);
    }

    lines.push(
      "",
      "## Architecture",
      "",
      "| Feature | Base | Arbitrum | Optimism |",
      "|---------|------|----------|----------|",
      "| Rollup Type | Optimistic (OP Stack) | Optimistic (Nitro) | Optimistic (OP Stack) |",
      "| Data Availability | EIP-4844 blobs | EIP-4844 blobs | EIP-4844 blobs |",
      "| Fraud Proofs | Permissioned | Decentralized (BOLD) | Permissioned |",
      "| Sequencer | Centralized (Coinbase) | Centralized (Offchain Labs) | Centralized (OP Labs) |",
      "| Governance | None (Coinbase operated) | ARB token DAO | OP token DAO + Citizens' House |",
      "",
      "## Summary",
      "",
      "- **Base**: Backed by Coinbase, strong retail onboarding, lowest fees post-Dencun",
      "- **Arbitrum**: Largest TVL, most DeFi protocols, Stylus for multi-language contracts",
      "- **Optimism**: OP Stack powers the Superchain (Base, Zora, Mode), strong governance model",
      "",
      "All three L2s use EIP-4844 blobs for data availability, keeping fees minimal compared to Ethereum L1.",
      "",
      "---",
      "*Comparison generated by @scout-alpha via 0xdirectping.com*",
    );

    return lines.join("\n");
  },
};
