import { createPublicClient, http, formatGwei } from "viem";
import { mainnet } from "viem/chains";
import type { Skill, SkillContext } from "./types.js";

const SAMPLE_COUNT = 30;
const SECONDS_PER_DAY = 86400;
const THIRTY_DAYS = SECONDS_PER_DAY * 30;

export const gasReportSkill: Skill = {
  name: "gas-report",
  keywords: [
    "gas",
    "price",
    "trends",
    "base",
    "ethereum",
    "l1",
    "report",
    "30",
    "days",
  ],

  async execute(ctx: SkillContext): Promise<string> {
    console.log("[gas-report] Fetching Base gas data...");

    // Get current block and estimate block 30 days ago
    const latestBlock = await ctx.publicClient.getBlock({ blockTag: "latest" });
    const currentBlockNum = latestBlock.number;
    // Base averages ~2s per block
    const blocksIn30Days = BigInt(THIRTY_DAYS / 2);
    const startBlock = currentBlockNum - blocksIn30Days;
    const blockStep = blocksIn30Days / BigInt(SAMPLE_COUNT);

    // Sample blocks across the 30-day range
    const samples: { day: number; gasPrice: bigint; timestamp: number }[] = [];
    for (let i = 0; i < SAMPLE_COUNT; i++) {
      const blockNum = startBlock + blockStep * BigInt(i);
      try {
        const block = await ctx.publicClient.getBlock({
          blockNumber: blockNum,
        });
        const dayIndex = Math.floor(
          (Number(block.timestamp) - Number(latestBlock.timestamp) + THIRTY_DAYS) /
            SECONDS_PER_DAY,
        );
        samples.push({
          day: dayIndex,
          gasPrice: block.baseFeePerGas ?? 0n,
          timestamp: Number(block.timestamp),
        });
      } catch {
        // Skip failed block fetches
      }
      // Rate limit
      await new Promise((r) => setTimeout(r, 300));
    }

    // Get current L1 gas for comparison
    let l1GasPrice = "N/A";
    try {
      const l1Client = createPublicClient({
        chain: mainnet,
        transport: http("https://eth.llamarpc.com"),
      });
      const l1Gas = await l1Client.getGasPrice();
      l1GasPrice = formatGwei(l1Gas);
    } catch {
      // L1 fetch is optional
    }

    // Get current Base gas
    const currentBaseGas = await ctx.publicClient.getGasPrice();

    // Group by day for averages
    const dayMap = new Map<number, bigint[]>();
    for (const s of samples) {
      const arr = dayMap.get(s.day) ?? [];
      arr.push(s.gasPrice);
      dayMap.set(s.day, arr);
    }

    // Build report
    const lines: string[] = [
      "# Base L2 Gas Trends Report (30 Days)",
      "",
      "## Current Snapshot",
      `- **Base L2 gas price**: ${formatGwei(currentBaseGas)} Gwei`,
      `- **Ethereum L1 gas price**: ${l1GasPrice} Gwei`,
      `- **Estimated L2 savings**: ~${l1GasPrice !== "N/A" ? Math.round((1 - Number(formatGwei(currentBaseGas)) / Number(l1GasPrice)) * 100) : "N/A"}% cheaper than L1`,
      "",
      "## Sampled Daily Averages",
      "",
      "| Day | Avg Base Fee (Gwei) |",
      "|-----|-------------------|",
    ];

    const sortedDays = Array.from(dayMap.keys()).sort((a, b) => a - b);
    for (const day of sortedDays) {
      const prices = dayMap.get(day)!;
      const avg =
        prices.reduce((a, b) => a + b, 0n) / BigInt(prices.length);
      lines.push(`| Day ${day + 1} | ${formatGwei(avg)} |`);
    }

    // Find peak
    let peakGas = 0n;
    let peakDay = 0;
    for (const [day, prices] of dayMap) {
      for (const p of prices) {
        if (p > peakGas) {
          peakGas = p;
          peakDay = day;
        }
      }
    }

    lines.push(
      "",
      "## Key Observations",
      "",
      `- **Peak gas**: ${formatGwei(peakGas)} Gwei (Day ${peakDay + 1})`,
      `- **Samples collected**: ${samples.length}/${SAMPLE_COUNT}`,
      `- Base L2 gas fees are consistently orders of magnitude cheaper than Ethereum L1`,
      `- Post-Dencun (EIP-4844), Base blob fees keep L2 costs minimal`,
      "",
      "---",
      "*Report generated by @scout-alpha via 0xdirectping.com*",
    );

    return lines.join("\n");
  },
};
