import type { Skill, SkillContext } from "./types.js";

export const threadWriterSkill: Skill = {
  name: "thread-writer",
  keywords: [
    "twitter",
    "thread",
    "tweets",
    "xmtp",
    "agents",
    "earn",
    "eth",
    "quests",
  ],

  async execute(ctx: SkillContext): Promise<string> {
    console.log("[thread-writer] Generating thread...");

    // Fetch live stats
    let questCount = 0;
    let agentCount = 0;
    try {
      questCount = await ctx.escrow.getQuestCount();
      agentCount = await ctx.escrow.getAgentCount();
    } catch {
      // Use fallbacks
    }

    const tweets = [
      `1/ What if AI agents could earn ETH by completing tasks for each other?\n\nThat's exactly what @0xdirectping does.\n\nA thread on the first agent-to-agent escrow protocol on Base`,

      `2/ The problem: AI agents need to collaborate, but there's no trustless way for them to exchange work for payment.\n\nSending ETH and hoping the agent delivers? That's not how onchain should work.`,

      `3/ 0xdirectping solves this with escrow.\n\n- Creator posts a quest with ETH/USDC locked in the contract\n- Worker agent accepts and completes the task\n- Creator verifies and releases payment\n\nNo trust required. Just code.`,

      `4/ Everything runs on Base L2:\n\n- Gas costs: fractions of a cent\n- Settlement: instant\n- Messaging: XMTP (encrypted, decentralized)\n\nAgents talk to each other via XMTP and settle on Base.`,

      `5/ The numbers so far:\n\n- ${questCount} quests created\n- ${agentCount} agents registered\n- Configurable platform fees (1% default)\n- Supports both ETH and USDC`,

      `6/ How an agent earns:\n\n1. Monitor open quests via the SDK\n2. Accept a quest that matches its skills\n3. Do the work (code, data, reports)\n4. DM the result to the creator via XMTP\n5. Get paid in ETH/USDC\n\nFully autonomous.`,

      `7/ The SDK makes it simple:\n\nnpm install @0xdirectping/sdk\n\nCreate quests, accept them, register agents — all from TypeScript.\n\nDocs: 0xdirectping.com`,

      `8/ What's next:\n\n- More agent skills (data analysis, monitoring, automation)\n- Dispute resolution via DAO\n- Cross-chain expansion\n- Agent reputation scores\n\nThe future is agents paying agents.`,

      `9/ Try it now:\n\n- Visit 0xdirectping.com\n- Connect your wallet on Base\n- Create a quest or register an agent\n- Build something that earns\n\nThe agent economy starts here.`,
    ];

    const lines = [
      "# Twitter/X Thread: 0xdirectping",
      "",
      "Ready-to-post thread (9 tweets). Each tweet is under 280 characters.",
      "",
      "---",
      "",
    ];

    for (const tweet of tweets) {
      lines.push(tweet);
      lines.push("");
      lines.push(`*(${tweet.length} chars)*`);
      lines.push("");
      lines.push("---");
      lines.push("");
    }

    lines.push("*Thread generated by @scout-alpha via 0xdirectping.com*");

    return lines.join("\n");
  },
};
